In [1]:
print ("Hello, Deborah!")

Hello, Deborah!

In [2]:
website = "Books to Scrape"

print(website)

Books to Scrape

In [3]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (3.0.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import requests

url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

200

In [5]:
print(response.text[:500])

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" /

In [6]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

print(soup.title.get_text())

    All products | Books to Scrape - Sandbox

In [7]:
first_book = soup.select_one("article.product_pod h3 a")

print(first_book.get_text(strip=True))

A Light in the ...

In [8]:
first_price = soup.select_one("article.product_pod .price_color")

print(first_price.get_text(strip=True))

Â£51.77

In [9]:
first_rating = soup.select_one("article.product_pod p.star-rating")

print(first_rating["class"][1])

Three

In [10]:
first_availability = soup.select_one(
    "article.product_pod .availability"
)

print(first_availability.get_text(strip=True))

In stock

In [11]:
book = {
    "Title": first_book.get_text(strip=True),
    "Price": first_price.get_text(strip=True),
    "Rating": first_rating["class"][1],
    "Availability": first_availability.get_text(strip=True)
}

print(book)

{'Title': 'A Light in the ...', 'Price': 'Â£51.77', 'Rating': 'Three', 'Availability': 'In stock'}

In [12]:
all_books = soup.select("article.product_pod")

print("Number of books on this page:", len(all_books))

Number of books on this page: 20

In [13]:
for item in all_books:
    title = item.select_one("h3 a")["title"]
    print(title)

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

In [14]:
books_data = []

for item in all_books:
    title = item.select_one("h3 a")["title"]
    price = item.select_one(".price_color").get_text(strip=True)
    rating = item.select_one("p.star-rating")["class"][1]
    availability = item.select_one(".availability").get_text(strip=True)

    book = {
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Availability": availability
    }

    books_data.append(book)

print(books_data[:3])

[{'Title': 'A Light in the Attic', 'Price': 'Â£51.77', 'Rating': 'Three', 'Availability': 'In stock'}, {'Title': 'Tipping the Velvet', 'Price': 'Â£53.74', 'Rating': 'One', 'Availability': 'In stock'}, {'Title': 'Soumission', 'Price': 'Â£50.10', 'Rating': 'One', 'Availability': 'In stock'}]

In [15]:
import pandas as pd

df = pd.DataFrame(books_data)

df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [16]:
df["Price"] = df["Price"].str.replace("Â", "", regex=False)

df.head()

                                   Title   Price Rating Availability
0                   A Light in the Attic  £51.77  Three     In stock
1                     Tipping the Velvet  £53.74    One     In stock
2                             Soumission  £50.10    One     In stock
3                          Sharp Objects  £47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  £54.23   Five     In stock

In [17]:
print(df.shape)

(20, 4)

In [18]:
page_2_url = "https://books.toscrape.com/catalogue/page-2.html"

page_2_response = requests.get(page_2_url)

print(page_2_response.status_code)

200

In [19]:
print(page_2_response.status_code)

200

In [20]:
page_2_soup = BeautifulSoup(page_2_response.text, "html.parser")

page_2_books = page_2_soup.select("article.product_pod")

print("Books found on page 2:", len(page_2_books))

Books found on page 2: 20

In [21]:
for item in page_2_books:
    title = item.select_one("h3 a")["title"]
    print(title)

In Her Wake
How Music Works
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
Chase Me (Paris Nights #2)
Black Dust
Birdsong: A Story in Pictures
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
Aladdin and His Wonderful Lamp
Worlds Elsewhere: Journeys Around Shakespeareâs Globe
Wall and Piece
The Four Agreements: A Practical Guide to Personal Freedom
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
The Elephant Tree
The Bear and the Piano
Sophie's World
Penny Maybe
Maude (1883-1993):She Grew Up with the country
In a Dark, Dark Wood
Behind Closed Doors
You can't bury them all: Poems

In [22]:
def greet():
    print("Hello, Web Scraping!")

greet()

Hello, Web Scraping!

In [23]:
def greet(name):
    print("Hello,", name)

greet("Deborah")
greet("Python")

Hello, Deborah
Hello, Python

In [24]:
def add_numbers(a, b):
    result = a + b
    return result

answer = add_numbers(5, 3)

print(answer)

8

In [25]:
def extract_book(item):
    title = item.select_one("h3 a")["title"]
    price = item.select_one(".price_color").get_text(strip=True)
    rating = item.select_one("p.star-rating")["class"][1]
    availability = item.select_one(".availability").get_text(strip=True)

    book = {
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Availability": availability
    }

    return book

In [26]:
first_book_data = extract_book(all_books[0])

print(first_book_data)

{'Title': 'A Light in the Attic', 'Price': 'Â£51.77', 'Rating': 'Three', 'Availability': 'In stock'}

In [27]:
page_1_data = []

for item in all_books:
    book = extract_book(item)
    page_1_data.append(book)

print("Total books collected:", len(page_1_data))

Total books collected: 20

In [28]:
print("Total books collected:", len(page_1_data))

Total books collected: 20

In [29]:
for page_number in range(1, 6):
    url = f"https://books.toscrape.com/catalogue/page-{page_number}.html"
    print(url)

https://books.toscrape.com/catalogue/page-1.html
https://books.toscrape.com/catalogue/page-2.html
https://books.toscrape.com/catalogue/page-3.html
https://books.toscrape.com/catalogue/page-4.html
https://books.toscrape.com/catalogue/page-5.html

In [30]:
for page_number in range(1, 6):
    url = f"https://books.toscrape.com/catalogue/page-{page_number}.html"
    response = requests.get(url)

    print("Page:", page_number, "| Status:", response.status_code)

Page: 1 | Status: 200
Page: 2 | Status: 200
Page: 3 | Status: 200
Page: 4 | Status: 200
Page: 5 | Status: 200

In [31]:
all_books_data = []

for page_number in range(1, 6):
    url = f"https://books.toscrape.com/catalogue/page-{page_number}.html"

    response = requests.get(url)
    page_soup = BeautifulSoup(response.text, "html.parser")

    books_on_page = page_soup.select("article.product_pod")

    for item in books_on_page:
        book = extract_book(item)
        all_books_data.append(book)

    print(f"Page {page_number}: collected {len(books_on_page)} books")

print("Total books collected:", len(all_books_data))

Page 1: collected 20 books
Page 2: collected 20 books
Page 3: collected 20 books
Page 4: collected 20 books
Page 5: collected 20 books
Total books collected: 100

In [32]:
df = pd.DataFrame(all_books_data)

print(df.shape)

df.head()

(100, 4)

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [33]:
def extract_book(item):
    title = item.select_one("h3 a")["title"]

    price = item.select_one(".price_color").get_text(strip=True)
    price = price.replace("Â", "")

    rating = item.select_one("p.star-rating")["class"][1]
    availability = item.select_one(".availability").get_text(strip=True)

    book = {
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Availability": availability
    }

    return book

In [34]:
all_books_data = []

for page_number in range(1, 6):
    url = f"https://books.toscrape.com/catalogue/page-{page_number}.html"

    response = requests.get(url)
    page_soup = BeautifulSoup(response.text, "html.parser")

    books_on_page = page_soup.select("article.product_pod")

    for item in books_on_page:
        book = extract_book(item)
        all_books_data.append(book)

print("Total books collected:", len(all_books_data))

Total books collected: 100

In [35]:
df = pd.DataFrame(all_books_data)

df["Price"].head()

0    £51.77
1    £53.74
2    £50.10
3    £47.82
4    £54.23
Name: Price, dtype: object

In [36]:
df.isnull().sum()

Title           0
Price           0
Rating          0
Availability    0
dtype: int64

In [37]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [38]:
print("Duplicate titles:", df["Title"].duplicated().sum())

Duplicate titles: 0

In [39]:
print(df.dtypes)

Title           object
Price           object
Rating          object
Availability    object
dtype: object

In [40]:
print(df["Price"].head())

0    £51.77
1    £53.74
2    £50.10
3    £47.82
4    £54.23
Name: Price, dtype: object

In [41]:
df["Price"] = df["Price"].str.replace("£", "", regex=False)

df["Price"] = df["Price"].astype(float)

print(df["Price"].head())

0    51.77
1    53.74
2    50.10
3    47.82
4    54.23
Name: Price, dtype: float64

In [42]:
average_price = df["Price"].mean()

print("Average book price: £", round(average_price, 2))

Average book price: £ 34.56

In [43]:
print("Cheapest book: £", df["Price"].min())
print("Most expensive book: £", df["Price"].max())

Cheapest book: £ 10.16
Most expensive book: £ 58.11

In [44]:
print("Cheapest book:")
print(df.loc[df["Price"].idxmin(), ["Title", "Price"]])

print("\nMost expensive book:")
print(df.loc[df["Price"].idxmax(), ["Title", "Price"]])

Cheapest book:
Title    Patience
Price       10.16
Name: 84, dtype: object

Most expensive book:
Title    The Death of Humanity: and the Case for Life
Price                                           58.11
Name: 68, dtype: object

In [45]:
rating_counts = df["Rating"].value_counts()

print(rating_counts)

Rating
Three    22
One      22
Five     19
Two      19
Four     18
Name: count, dtype: int64

In [46]:
availability_counts = df["Availability"].value_counts()

print(availability_counts)

Availability
In stock    100
Name: count, dtype: int64

In [47]:
import time

In [48]:
all_books_data = []

for page_number in range(1, 51):
    url = f"https://books.toscrape.com/catalogue/page-{page_number}.html"

    response = requests.get(url, timeout=15)

    if response.status_code == 200:
        page_soup = BeautifulSoup(response.text, "html.parser")
        books_on_page = page_soup.select("article.product_pod")

        for item in books_on_page:
            book = extract_book(item)
            all_books_data.append(book)

        print(f"Page {page_number}: collected {len(books_on_page)} books")
    else:
        print(f"Page {page_number}: failed with status {response.status_code}")

    time.sleep(1)

print("Total books collected:", len(all_books_data))

Page 1: collected 20 books
Page 2: collected 20 books
Page 3: collected 20 books
Page 4: collected 20 books
Page 5: collected 20 books
Page 6: collected 20 books
Page 7: collected 20 books
Page 8: collected 20 books
Page 9: collected 20 books
Page 10: collected 20 books
Page 11: collected 20 books
Page 12: collected 20 books
Page 13: collected 20 books
Page 14: collected 20 books
Page 15: collected 20 books
Page 16: collected 20 books
Page 17: collected 20 books
Page 18: collected 20 books
Page 19: collected 20 books
Page 20: collected 20 books
Page 21: collected 20 books
Page 22: collected 20 books
Page 23: collected 20 books
Page 24: collected 20 books
Page 25: collected 20 books
Page 26: collected 20 books
Page 27: collected 20 books
Page 28: collected 20 books
Page 29: collected 20 books
Page 30: collected 20 books
Page 31: collected 20 books
Page 32: collected 20 books
Page 33: collected 20 books
Page 34: collected 20 books
Page 35: collected 20 books
Page 36: collected 20 books
Page 37: collected 20 books
Page 38: collected 20 books
Page 39: collected 20 books
Page 40: collected 20 books
Page 41: collected 20 books
Page 42: collected 20 books
Page 43: collected 20 books
Page 44: collected 20 books
Page 45: collected 20 books
Page 46: collected 20 books
Page 47: collected 20 books
Page 48: collected 20 books
Page 49: collected 20 books
Page 50: collected 20 books
Total books collected: 1000

In [49]:
import pandas as pd

df = pd.DataFrame(all_books_data)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (1000, 4)

                                   Title   Price Rating Availability
0                   A Light in the Attic  £51.77  Three     In stock
1                     Tipping the Velvet  £53.74    One     In stock
2                             Soumission  £50.10    One     In stock
3                          Sharp Objects  £47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  £54.23   Five     In stock

In [50]:
# Remove the pound symbol from prices
df["Price"] = df["Price"].str.replace("£", "", regex=False)

# Convert prices from text to numbers
df["Price"] = df["Price"].astype(float)

# Check the result
print(df["Price"].head())
print("\nPrice data type:", df["Price"].dtype)

0    51.77
1    53.74
2    50.10
3    47.82
4    54.23
Name: Price, dtype: float64

Price data type: float64

In [51]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nDuplicate book titles:")
print(df["Title"].duplicated().sum())

Missing values:
Title           0
Price           0
Rating          0
Availability    0
dtype: int64

Duplicate rows:
0

Duplicate book titles:
1

In [52]:
duplicate_books = df[df["Title"].duplicated(keep=False)]

print(duplicate_books)

                      Title  Price Rating Availability
236  The Star-Touched Queen  46.02   Five     In stock
358  The Star-Touched Queen  32.30   Five     In stock

In [53]:
print("Average price: £", round(df["Price"].mean(), 2))
print("Cheapest price: £", df["Price"].min())
print("Most expensive price: £", df["Price"].max())

Average price: £ 35.07
Cheapest price: £ 10.0
Most expensive price: £ 59.99

In [54]:
rating_counts = df["Rating"].value_counts()

print(rating_counts)

Rating
One      226
Three    203
Five     196
Two      196
Four     179
Name: count, dtype: int64

In [55]:
print(df["Availability"].value_counts())

Availability
In stock    1000
Name: count, dtype: int64

In [56]:
df.to_csv("books_scraped.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [57]:
from google.colab import files

files.download("books_scraped.csv")